services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: douyin-api
    volumes:
      - data:/data
    env_file:
      - .env.production
    ports:
      - "${APP_PORT:-8000}:8000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: douyin-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data:/data:ro
      - nginx-secrets:/etc/nginx/secrets
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_SSL_PORT:-443}:443"
    depends_on:
      - app
    restart: always

volumes:
  data:
  nginx-secrets: